### ISSUE TITLE
Namemc returning odd location results

### ISSUE THREAD

**Issue by Kqzz** [Kqzz/MC-API#3]
On certain profiles the namemc location data is completely off. I believe the cause of this is there being no location linked but namemc emerald being on the account. An example of this is the profile [hy](https://api.kqzz.me/api/mojang/user/hy?namemc=true).

**Comment by wh-at** [comment]
Same profile returning no location now, even though it's `Kuwait`, just thought I'd comment to make you aware if not already

**Comment by Kqzz** [comment]
Ok. Will look into this.
